<?php

namespace AppBundle\Repository;

/**
 * Pack_ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pack_ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
